### ISSUE TITLE
haven't you tried to unfreeze some layer to learn them?

### ISSUE THREAD

**Issue by SankBad** [sebastianbk/finetuned-resnet50-keras#1]

**Comment by sebastianbk** [comment]
If you refer to train on all of the layers (rather than just the final Dense layer), you can do so by setting each of the layers in the network to be trainable. That is done here:

https://github.com/sebastianbk/finetuned-resnet50-keras/blob/dab2213c0e431e311229846ed52993e4e1ed5c91/resnet50_train.py#L36

Is that what you mean?

**Comment by SankBad** [comment]
Oh ok got it. Actually, I was confused about how many layers I should freeze in ResNet50 depending on architecture then I got to know it works better when we keep layer after 175 unfreeze.
Thanks!
